# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.addresstype:
        class: Civieta\AppBundle\Form\Types\AddressType
        tags:
            - { name: form.type, alias: addresstype }

    app.appextension:
        class: Civieta\AppBundle\Twig\AppExtension
        calls:
            - [initRuntime, [@twig]]
        tags:
            - { name: twig.extension }